export * from "../gen/common_pb.js";
export * from "../gen/protocol2_pb.js";
export * from "../gen/protocol3_pb.js";

// TODO: automate updating this part?

import type { Message, PlainMessage } from "@bufbuild/protobuf";
import {
  ClientBoundCombined,
  CPacketAnimation,
  CPacketBlockAction,
  CPacketBlockUpdate,
  CPacketChangeServers,
  CPacketCloseWindow,
  CPacketConfirmTransaction,
  CPacketDestroyEntities,
  CPacketDisconnect,
  CPacketEntityAction,
  CPacketEntityAttach,
  CPacketEntityEffect,
  CPacketEntityEquipment,
  CPacketEntityMetadata,
  CPacketEntityPositionAndRotation,
  CPacketEntityProperties,
  CPacketEntityRelativePositionAndRotation,
  CPacketEntityStatus,
  CPacketEntityVelocity,
  CPacketExplosion,
  CPacketJoinGame,
  CPacketLeaderboard,
  CPacketLocalStorage,
  CPacketMessage,
  CPacketOpenShop,
  CPacketOpenWindow,
  CPacketParticles,
  CPacketPlayerList,
  CPacketPlayerPosition,
  CPacketPlayerPosLook,
  CPacketPlayerReconciliation,
  CPacketPong,
  CPacketQueueNext,
  CPacketRemoveEntityEffect,
  CPacketRespawn,
  CPacketScoreboard,
  CPacketServerInfo,
  CPacketServerMetadata,
  CPacketSetExperience,
  CPacketSetSlot,
  CPacketShopProperties,
  CPacketSignEditorOpen,
  CPacketSoundEffect,
  CPacketSpawnEntity,
  CPacketSpawnExperienceOrb,
  CPacketSpawnPlayer,
  CPacketTabComplete,
  CPacketTimeUpdate,
  CPacketTitle,
  CPacketUpdate,
  CPacketUpdateCommandBlock,
  CPacketUpdateHealth,
  CPacketUpdateLeaderboard,
  CPacketUpdateScoreboard,
  CPacketUpdateSign,
  CPacketUpdateStatus,
  CPacketUseBed,
  CPacketWindowItems,
  CPacketWindowProperty,
  SPacketAdminAction,
  SPacketAnalytics,
  SPacketBreakBlock,
  SPacketClick,
  SPacketClickWindow,
  SPacketCloseWindow,
  SPacketConfirmTransaction,
  SPacketCraftItem,
  SPacketEnchantItem,
  SPacketEntityAction,
  SPacketHeldItemChange,
  SPacketLoginStart,
  SPacketMessage,
  SPacketOpenShop,
  SPacketPing,
  SPacketPlaceBlock,
  SPacketPlayerAbilities,
  SPacketPlayerAction,
  SPacketPlayerInput,
  SPacketPlayerPosLook,
  SPacketQueueNext,
  SPacketRequestChunk,
  SPacketRespawn,
  SPacketTabComplete,
  SPacketUpdateCommandBlock,
  SPacketUpdateInventory,
  SPacketUpdateSign,
  SPacketUseEntity,
  SPacketUseItem,
  CPacketScriptData,
  CPacketScriptLog,
  SPacketScriptAction,
} from "../gen/protocol2_pb.js";
import { CPacketChunkData } from "../gen/protocol3_pb.js";

export const CPACKET_MAP = {
  CPacketAnimation,
  CPacketBlockAction,
  CPacketBlockUpdate,
  CPacketChangeServers,
  CPacketChunkData,
  CPacketCloseWindow,
  CPacketConfirmTransaction,
  CPacketDestroyEntities,
  CPacketDisconnect,
  CPacketEntityAction,
  CPacketEntityEquipment,
  CPacketEntityMetadata,
  CPacketEntityPositionAndRotation,
  CPacketEntityRelativePositionAndRotation,
  CPacketEntityStatus,
  CPacketEntityVelocity,
  CPacketExplosion,
  CPacketJoinGame,
  CPacketLeaderboard,
  CPacketLocalStorage,
  CPacketMessage,
  CPacketOpenWindow,
  CPacketParticles,
  CPacketPlayerList,
  CPacketPlayerPosition,
  CPacketPlayerPosLook,
  CPacketPlayerReconciliation,
  CPacketPong,
  CPacketRespawn,
  CPacketScoreboard,
  CPacketServerInfo,
  CPacketSetSlot,
  CPacketSignEditorOpen,
  CPacketSoundEffect,
  CPacketSpawnEntity,
  CPacketSpawnPlayer,
  CPacketTabComplete,
  CPacketTitle,
  CPacketUpdate,
  CPacketUpdateHealth,
  CPacketUpdateLeaderboard,
  CPacketUpdateScoreboard,
  CPacketUpdateSign,
  CPacketUpdateStatus,
  CPacketWindowItems,
  CPacketWindowProperty,
  CPacketUseBed,
  CPacketQueueNext,
  CPacketSpawnExperienceOrb,
  CPacketSetExperience,
  CPacketOpenShop,
  CPacketShopProperties,
  CPacketEntityProperties,
  CPacketEntityEffect,
  CPacketRemoveEntityEffect,
  CPacketUpdateCommandBlock,
  CPacketEntityAttach,
  CPacketServerMetadata,
  CPacketTimeUpdate,
  ClientBoundCombined,
  CPacketScriptData,
  CPacketScriptLog,
} as const;

export const SPACKET_MAP = {
  SPacketAdminAction,
  SPacketAnalytics,
  SPacketClickWindow,
  SPacketCloseWindow,
  SPacketConfirmTransaction,
  SPacketEnchantItem,
  SPacketEntityAction,
  SPacketHeldItemChange,
  SPacketLoginStart,
  SPacketMessage,
  SPacketOpenShop,
  SPacketPing,
  SPacketPlayerAbilities,
  SPacketPlayerAction,
  SPacketPlayerPosLook,
  SPacketRespawn,
  SPacketTabComplete,
  SPacketUpdateSign,
  SPacketUseEntity,
  SPacketUpdateCommandBlock,
  SPacketQueueNext,
  SPacketPlayerInput,
  SPacketBreakBlock,
  SPacketClick,
  SPacketCraftItem,
  SPacketPlaceBlock,
  SPacketRequestChunk,
  SPacketUpdateInventory,
  SPacketUseItem,
  SPacketScriptAction,
} as const;

type AnyPacketMap = typeof CPACKET_MAP & typeof SPACKET_MAP;

export const NAME_TO_ID: Record<string, number> = {};
export const ID_TO_PACKET: Record<string, PlainMessage<Message>> = {};
export const ID_TO_NAME: Record<number, keyof AnyPacketMap> = {};

function fixedEntries<K extends string | number | symbol, V>(
  x: Record<K, V>,
): [K, V][] {
  return Object.entries(x) as [K, V][]; // holy who wrote these typings LOL, there should be an extra type parameter for the key :sob:
}

let currentId = 0;
for (const [i, v] of fixedEntries(CPACKET_MAP)) {
  NAME_TO_ID[i] = currentId;
  ID_TO_PACKET[currentId] = v;
  ID_TO_NAME[currentId] = i;
  currentId++;
}

for (const [i, v] of fixedEntries(SPACKET_MAP)) {
  NAME_TO_ID[i] = currentId;
  ID_TO_PACKET[currentId] = v;
  ID_TO_NAME[currentId] = i;
  currentId++;
}
